### PR TITLE
Jabulani branch

### PR DESCRIPTION
**Pull request by Jabulani-N**
fixed pycodestyle on console.py.
also created a gitignore.

### CODE REVIEW

**Comment by Jabulani-N** [comment]
fixed do_create (from when I broke it in an earlier commit on my branch.
fixed the console so it can now receive names.
Have not fixed the fact that it complains every time it opens.

**Comment by Jabulani-N** [comment]
fixed console complaining every time it is opened.
console can no longer create new attributes in classes

**Comment by Kveltri22** [comment]
Approved

**Comment by Kveltri22** [comment]
Approved

**Review by Kveltri22 — APPROVED** [review]

**Comment by Kveltri22** [comment]
Looks good

**Pull request merged**
